### ISSUE TITLE
Node mcu 12e with 2.4 TFT touch

### ISSUE THREAD

**Issue by wisesokol** [himikat123/Weather-Monitor-BIM#1]
День добрый.
Планирую использовать NOde mcu. датчиков не будет. Погода только с интернета.
На что следует обратить внимание для данной компановки в прошивке? К сожалению не особо силен в коде.

**Comment by himikat123** [comment]
Здравствуйте. Если в коде не сильны прошивайте скомпиллированный bin файл. Без датчиков будет все работать. Все настройки делаются через Веб-интерфейс, в прошивке править ничего не нужно.
