### ISSUE TITLE
Error boxes

### ISSUE THREAD

**Issue by micko-24** [himikat123/Weather-Monitor-BIM#12]
Dear Sir,
I had a box made according to your designs and the manufacturer informed me of these errors.

cover.stl
1 | Multi-shells detected
2 | Possible noise shells detected
3 | < 0.8mm wall thickness detected

reset_btn.stl
1 | Multi-shells detected
2 | < 0.8mm wall thickness detected

settings_btn.stl
1 | Multi-shells detected
2 | Possible noise shells detected
3 | < 0.8mm wall thickness detected

Can it be corrected?
Thanks.

**Comment by himikat123** [comment]
Hi micko-24, thanks for reporting.  I have corrected and updated all 3D print files

**Comment by micko-24** [comment]
Thank you, I just got a 3d printer, so I will print the new versions of the housing .
